# Generated by Django 3.1 on 2020-08-10 05:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(help_text='Введите координаты в формате WKT, например, POLYGON((30 10, 40 40, 20 40, 10 20, 30 10))', srid=4326, verbose_name='Территория склада')),
                ('contents', models.JSONField(default={'composition': {'Fe': 0, 'SiO2': 0}, 'weight': 0}, verbose_name='Груз, гр')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='TrackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('max_load_capacity', models.PositiveIntegerField(verbose_name='Максимальная грузоподъёмность')),
            ],
            options={
                'verbose_name': 'Модель самосвалов',
                'verbose_name_plural': 'Модели самосвалов',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('contents', models.JSONField(default={'composition': {'Fe': 0, 'SiO2': 0}, 'weight': 0}, verbose_name='Груз, гр')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unloading.trackmodel', verbose_name='Модель самосвала')),
            ],
            options={
                'verbose_name': 'Самосвал',
                'verbose_name_plural': 'Самосвалы',
            },
        ),
    ]
