# Generated by Django 3.1 on 2020-08-10 07:15

from django.db import migrations, models
import unloading.models


class Migration(migrations.Migration):

    dependencies = [
        ('unloading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='contents',
            field=models.JSONField(default=unloading.models.getDefaultContents, help_text='Например, {"weight": 900000, "composition": {"SiO2": 306000, "Fe": 585000}}', verbose_name='Содержимое, кг'),
        ),
        migrations.AlterField(
            model_name='track',
            name='contents',
            field=models.JSONField(default=unloading.models.getDefaultContents, help_text='Например, {"weight": 100000, "composition": {"SiO2": 32000, "Fe": 67000}}', verbose_name='Груз, кг'),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Бортовой номер'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='max_load_capacity',
            field=models.PositiveIntegerField(verbose_name='Максимальная грузоподъёмность, кг'),
        ),
    ]
